language: python
python:
- '3.8'
- "nightly"  # nightly build
# Command to install the dependencies
install:
- pip install -r requirements.txt
# Send build notifications to the following email addresses
notifications:
  email:
    recipients:
      - student@example.com
      - lecturer@example.com
    on_success: always
    on_failure: always 
script: 
  - echo "no scripts"
